### ISSUE TITLE
Add texture based feature extraction (radiomics)

### ISSUE THREAD

**Issue by umgpy** [CBICA/GaNDLF#17]
**Is your feature request related to a problem? Please describe.**
As texture features are increasingly being used in medical imaging, it would be nice to have support for same here.

**Describe the solution you'd like**
Integrate popular radiomics package [pyradiomics](https://github.com/AIM-Harvard/pyradiomics).

**Describe alternatives you've considered**
GPU based radiomics package [cuRadiomics](https://github.com/jiaoyining/cuRadiomics). Although it might be unstable/not actively developed. Open to any other suggestions.

**Additional context**
None

**Comment by sarthakpati** [comment]
Hi @umgpy,

Thanks for your interest in GaNDLF! 

Is there value in adding engineered features for a DL algorithm? The reason why I ask this is because the entire idea of convolutional filters is to allow a network to judge what the "best" combination of filters is going to be for a particular problem statement. What this means is that the same network architecture can end up dramatically different final filters for brain tumor segmentation and brain extraction (you can read more about this on any of the Grad-Cam or related papers). Taggin @Geeks-Sid to provide more elaboration and details.

FYI, we have our own radiomics package, [CaPTk](https://github.com/CBICA/CaPTk/), which is also IBSI compliant and pretty good, too. 😉 

Cheers,
Sarthak

**Comment by umgpy** [comment]
Hi @sarthakpati ,

Sorry for the late reply. While hand engineered texture features are not commonly used for segmentation tasks, but can be passed on as an additional input to the CNN  for classification tasks.
Thanks i'll check it out.

Ahh I have used CaPTk previously for automated segmentations didn't it had radiomics too. Thanks!

**Comment by sarthakpati** [comment]
> but can be passed on as an additional input to the CNN for classification tasks

Could be interesting to explore. I don't think anyone in our side currently has this bandwidth, but if you can put in a PR for this and generate some results, it would make for a great contribution!

**Comment by umgpy** [comment]
Thanks I'll try to implement a working version!

**Comment by Geeks-Sid** [comment]
Feel free to open a PR when you are able to add this. Closing for now.
